# sample3.py
# Create a red-cyan anaglyph image (stereo 3D) from two rendered views.

from PIL import Image


def blend_anaglyph(left_path, right_path, out_path):
    left = Image.open(left_path).convert('RGB')
    right = Image.open(right_path).convert('RGB')

    l = left.split()
    r = right.split()

    # Red channel from left, green+blue from right
    anaglyph = Image.merge('RGB', (l[0], r[1], r[2]))
    anaglyph.save(out_path)


if __name__ == '__main__':
    # Use the stereo pair generated by sample1
    blend_anaglyph('/tmp/vr_left.png', '/tmp/vr_right.png', '/tmp/vr_anaglyph.png')
    print('Saved anaglyph as /tmp/vr_anaglyph.png')
